---
name: CI

on:
  push:
    branches: ['main']
    paths:
      - '**.go'
      - 'go.mod'
      - 'go.sum'
      - '.golangci.yml'
      - '.golangci.yaml'
  pull_request:
    branches: ['main']
    paths:
      - '**.go'
      - 'go.mod'
      - 'go.sum'
      - '.golangci.yml'
      - '.golangci.yaml'

permissions:
  contents: read

jobs:
  ci:
    uses: oszuidwest/.github-templates/.github/workflows/go-ci.yml@v2
